import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const core=fs.readFileSync(new URL('../../crates/core/src/storage.rs',import.meta.url),'utf8');const model=fs.readFileSync(new URL('../../crates/core/src/model.rs',import.meta.url),'utf8');const runtime=fs.readFileSync(new URL('../../crates/runtime/src/lib.rs',import.meta.url),'utf8');const protocol=fs.readFileSync(new URL('../../crates/protocol/src/lib.rs',import.meta.url),'utf8');const tauri=fs.readFileSync(new URL('../../src-tauri/src/lib.rs',import.meta.url),'utf8');const tauriCargo=fs.readFileSync(new URL('../../src-tauri/Cargo.toml',import.meta.url),'utf8');const sdk=fs.readFileSync(new URL('../../packages/sdk/src/index.ts',import.meta.url),'utf8');
test('D5 HostServices keeps native picker at Tauri boundary',()=>{assert.match(runtime,/pub trait RuntimeHostServices[\s\S]*choose_directory[\s\S]*confirm_export_replace/);assert.match(runtime,/bind_with_host_services/);assert.match(tauri,/impl RuntimeHostServices for TauriHostServices/);assert.match(tauri,/blocking_pick_folder/);assert.match(tauri,/MessageDialogButtons::YesNo/);assert.match(tauriCargo,/tauri-plugin-dialog = "=2\.7\.3"/);assert.doesNotMatch(core,/tauri_plugin_dialog|AppHandle|blocking_pick_folder/)});
test('D5 grants and presets live in existing registry and public wire omits physical path',()=>{assert.match(core,/CREATE TABLE IF NOT EXISTS directory_grants\([^;]*physical_path TEXT/);assert.match(core,/CREATE TABLE IF NOT EXISTS export_presets\(/);assert.match(model,/pub struct DirectoryGrantRecord[\s\S]*physical_path: String/);const wire=protocol.slice(protocol.indexOf('pub struct DestinationGrantWire'),protocol.indexOf('pub struct CreateDestinationGrantRequest'));assert.doesNotMatch(wire,/path|physical/i);assert.match(wire,/id: String[\s\S]*label: String[\s\S]*capability/);assert.match(runtime,/DestinationReadOnly/);assert.match(runtime,/DestinationGrantRevoked/)});
test('D5 export is content agnostic, file-atomic and supports deterministic conflict policies',()=>{const native=core.slice(core.indexOf('pub fn native_export'),core.indexOf('pub fn export_space_zip'));for(const policy of ['Replace','Skip','Rename','Ask','UpdateChanged'])assert.match(core,new RegExp(`ExportConflictPolicy::${policy}`));assert.match(native,/sha256_file\(&target0\)/);assert.match(native,/copy_file_atomic_stage/);assert.match(core,/atomic_replace\(temp,target\)/);assert.match(native,/vontaqfs-native-export/);assert.match(native,/checksum/);assert.match(native,/guarantee:\s*"file-atomic"/);assert.doesNotMatch(native,/extension\(\).*match|serde_json::from_slice.*source|decrypt|recompress/i)});
test('D5 SDK exposes opaque destination, presets and high-level export with shared operation engine',()=>{assert.match(sdk,/interface DestinationAPI[\s\S]*create[\s\S]*list[\s\S]*revoke/);assert.match(sdk,/interface ExportPresetAPI[\s\S]*save[\s\S]*list[\s\S]*delete/);assert.match(sdk,/async export\(source: string \| readonly string\[\][\s\S]*new OperationObserver[\s\S]*runTracked/);assert.doesNotMatch(sdk,/destinationPath\s*:/)});
test('D5 public runtime routes keep physical destination resolution server-side',()=>{for(const route of ['/v1/destinations/create','/v1/destinations/list','/v1/destinations/revoke','/v1/exports/start','/v1/export-presets/save','/v1/export-presets/list','/v1/export-presets/delete'])assert.ok(runtime.includes(route),route);assert.match(runtime,/state\.authorize_space\(&session,&input\.space_id\)/);assert.match(runtime,/host\.choose_directory/);assert.match(runtime,/storage\.get_directory_grant/)});
test('D5 update-changed never turns a write-only saved destination into implicit read access',()=>{assert.match(runtime,/UpdateChanged[\s\S]{0,220}!grant\.capability\.can_read\(\)[\s\S]{0,180}PermissionDenied/);assert.match(core,/update-changed requires a read-write destination grant/)});
test('D5 interrupted native export is journaled and update-changed consults exported checksum metadata',()=>{const native=core.slice(core.indexOf('pub fn native_export'),core.indexOf('pub fn export_space_zip'));assert.match(native,/prepare_native_export_journal/);assert.match(native,/load_native_export_manifest_checksums/);assert.match(core,/vontaqfs-native-export-journal/);assert.match(core,/\.vontaqfs-export-interrupted-/);assert.match(native,/previous_manifest\.get\(&item\.path\)/);assert.match(native,/write_native_export_journal\(&destination_root, "cancelled"/);assert.match(native,/write_native_export_journal\(&destination_root, "failed"/)});
