import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const core=fs.readFileSync(new URL('../../crates/core/src/storage.rs',import.meta.url),'utf8');
const model=fs.readFileSync(new URL('../../crates/core/src/model.rs',import.meta.url),'utf8');
const runtime=fs.readFileSync(new URL('../../crates/runtime/src/lib.rs',import.meta.url),'utf8');
const protocol=fs.readFileSync(new URL('../../crates/protocol/src/lib.rs',import.meta.url),'utf8');
const tauri=fs.readFileSync(new URL('../../src-tauri/src/lib.rs',import.meta.url),'utf8');
const sdk=fs.readFileSync(new URL('../../packages/sdk/src/index.ts',import.meta.url),'utf8');
const desktopApi=fs.readFileSync(new URL('../../apps/desktop/src/desktopApi.ts',import.meta.url),'utf8');
const desktopMain=fs.readFileSync(new URL('../../apps/desktop/src/main.tsx',import.meta.url),'utf8');

function section(source,start,end){const a=source.indexOf(start);assert.notEqual(a,-1,`missing ${start}`);const b=end?source.indexOf(end,a):source.length;assert.notEqual(b,-1,`missing ${end}`);return source.slice(a,b)}

test('D7 portable backup is versioned, exact-byte oriented and excludes auth secrets',()=>{const backup=section(core,'pub fn create_portable_backup','pub fn restore_portable_backup');assert.match(backup,/vontaqfs-backup\.json/);assert.match(backup,/PORTABLE_BACKUP_FORMAT_VERSION/);assert.match(backup,/sha256_file_cancellable/);assert.match(backup,/add_file_verified_cancellable/);assert.match(backup,/ensure_disk_reserve/);assert.match(backup,/record\.etag/);assert.doesNotMatch(backup,/pairing|credential|session|token/i);const manifest=section(core,'struct PortableBackupManifest','struct SnapshotDiskManifest');assert.doesNotMatch(manifest,/pairing|credential|session|token/i);assert.match(model,/pub struct PortableBackupReport/)});

test('D7 restore stages before commit, requires explicit replacement, and never grants pairing',()=>{const restore=section(core,'pub fn restore_portable_backup','pub fn create_snapshot');assert.match(restore,/ensure_disk_reserve/);assert.match(restore,/restore-staging/);assert.match(restore,/RestoreConflictPolicy::Fail/);assert.match(restore,/progress\("committing"[\s\S]*false\)/);assert.match(restore,/pairing_granted: false/);assert.match(restore,/delete_application_if_unused/);assert.match(restore,/commit_staged_space_replace/);assert.doesNotMatch(restore,/create_pairing|credential_hash/);const commit=section(core,'fn commit_staged_space_replace','fn row_directory_grant');assert.match(commit,/fs::rename\(&data_root, &old_data\)/);assert.match(commit,/fs::rename\(staging_data, &data_root\)/);assert.match(commit,/DELETE FROM file_entries/);assert.match(commit,/DELETE FROM kv_entries/)});

test('D7 snapshot baseline stores immutable copied payload plus file and KV metadata',()=>{const snapshots=section(core,'pub fn create_snapshot','fn snapshot_records');assert.match(snapshots,/snp_/);assert.match(snapshots,/ensure_disk_reserve/);assert.match(snapshots,/copy_file_verified/);assert.match(snapshots,/SnapshotDiskManifest/);assert.match(snapshots,/snapshot_file_entries/);assert.match(snapshots,/snapshot_kv_entries/);assert.match(snapshots,/pub fn list_snapshots/);assert.match(snapshots,/pub fn delete_snapshot/);assert.match(snapshots,/pub fn restore_snapshot/);assert.match(model,/pub struct SnapshotRecord[\s\S]*source_generation/)});

test('D7 snapshot restore is cancellable only before non-cancellable commit and reports guarantee truthfully',()=>{const restore=section(core,'pub fn restore_snapshot','fn snapshot_records');assert.match(restore,/progress\("staging"[\s\S]*true\)/);assert.match(restore,/OperationCancelled/);assert.match(restore,/ensure_no_symlink_escape\(&snapshot_data/);assert.match(restore,/progress\("committing"[\s\S]*false\)/);assert.match(restore,/guarantee: "directory-swap"/);assert.match(runtime,/set_operation_cancellable\(&op_progress, cancellable\)/)});

test('D7 SDK exposes space-scoped snapshots and Runtime enforces operation ownership routes',()=>{assert.match(sdk,/readonly snapshots: SnapshotAPI/);assert.match(sdk,/\/v1\/snapshots\/create/);assert.match(sdk,/\/v1\/snapshots\/restore/);assert.match(runtime,/"POST", "\/v1\/snapshots\/create"/);assert.match(runtime,/"POST", "\/v1\/snapshots\/list"/);assert.match(runtime,/"POST", "\/v1\/snapshots\/restore"/);assert.match(runtime,/"POST", "\/v1\/snapshots\/delete"/);assert.match(runtime,/authorize_space\(&session, &input\.space_id\)/);assert.match(protocol,/SnapshotNotFound/);assert.match(protocol,/SnapshotRestoreConflict/)});

test('D7 Desktop host and visible admin UI can backup, restore and manage snapshots without Figma running',()=>{assert.match(tauri,/start_space_backup_default/);assert.match(tauri,/\.vontaqfs-backup/);assert.match(tauri,/start_backup_restore_picker/);assert.match(tauri,/list_space_snapshots/);assert.match(tauri,/start_create_snapshot/);assert.match(tauri,/start_restore_snapshot/);assert.match(runtime,/portable restore requires all client sessions to be disconnected/);assert.match(runtime,/lock_global_maintenance/);assert.match(runtime,/storage is temporarily locked by a privileged restore operation/);assert.match(runtime,/start_backup_space/);assert.match(runtime,/start_restore_backup/);assert.match(desktopApi,/backupSpace:/);assert.match(desktopApi,/restoreBackup:/);assert.match(desktopApi,/snapshots:/);assert.match(desktopApi,/createSnapshot:/);assert.match(desktopApi,/restoreSnapshot:/);assert.match(desktopApi,/deleteSnapshot:/);assert.match(desktopMain,/Restore backup/);assert.match(desktopMain,/Create snapshot/);assert.match(desktopMain,/Snapshots \(\{snapshots\.length\}\)/);assert.match(desktopMain,/desktopApi\.restoreSnapshot/);assert.match(desktopMain,/desktopApi\.deleteSnapshot/)});
